---
sudo: false
language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cvs
            - g++-6
            - build-essential # build-essential is already the newest version (11.6ubuntu6).

compiler:
  # - clang # => Build dependency gcc3-c>=3.3.5nb1: NOT found
  - gcc

cache:
  directories:
    # - $HOME/...

matrix:
  fast_finish: true
  include:
  allow_failures:

before_install:
    # - env
    - pwd
    - [[ -v CC ]] && printenv CC
    - [[ -v CXX ]] && printenv CXX
    - bash -c "[[ -x `which gcc` ]] && gcc --version"
    - bash -c "[[ -x `which g++` ]] && g++ --version"
    - bash -c "[[ -x `which gcc-7` ]] && gcc-7 --version"
    - bash -c "[[ -x `which g++-7` ]] && g++-7 --version"
    - bash -c "[[ -x `which gcc-6` ]] && gcc-6 --version"
    - bash -c "[[ -x `which g++-6` ]] && g++-6 --version"
    - bash -c "[[ -x `which gcc-5` ]] && gcc-5 --version"
    - bash -c "[[ -x `which g++-5` ]] && g++-5 --version"
    - bash -c "[[ -x `which gcc-4.9` ]] && gcc-4.9 --version"
    - bash -c "[[ -x `which g++-4.9` ]] && g++-4.9 --version"
    - ssh -o StrictHostKeyChecking=no anoncvs@anoncvs.netbsd.org cvs
    - if [[ -x `which cvs` ]]; then  travis_wait cvs -Q -d anoncvs@anoncvs.netbsd.org:/cvsroot co -rpkgsrc-2017Q2 -P pkgsrc; else git clone https://github.com/NetBSD/pkgsrc.git ; env PWD=${PWD}/pkgsrc git checkout pkgsrc_2017Q1; fi
    # The program 'cvs' is currently not installed. 2017-09-07
    # - git clone https://github.com/NetBSD/pkgsrc.git ; env PWD=${PWD}/pkgsrc git checkout pkgsrc-2017Q2
    - ls pkgsrc/bootstrap
    - export SH=/bin/bash
    - pkgsrc/bootstrap/bootstrap --help
    - pkgsrc/bootstrap/bootstrap --unprivileged --prefix=${HOME}/pkg
    - PATH=${HOME}/pkg/sbin:${HOME}/pkg/bin:${PATH}
    - MANPATH=${HOME}/pkg/man:${MANPATH}
    - ls ${HOME}/pkg

# install:

# before_script:

script:
    - ls pkgsrc/*

# after_success:

# https://github.com/agjohnson/ohess-blog/blob/master/pub/using-pkgsrc-on-debian-squeeze.rst
# https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
