---
sudo: false
language: c

addons:
    apt:
        packages:
            - cvs

compiler:
  - clang
  # - gcc

cache:
  directories:
    # - $HOME/...

matrix:
  fast_finish: true
  include:
  allow_failures:

before_install:
    - env
    - pwd
    - yes | cvs -d anoncvs@anoncvs.netbsd.org:/cvsroot co -rpkgsrc-2017Q2 -P pkgsrc
    # The program 'cvs' is currently not installed. 2017-09-07
    # - git clone https://github.com/NetBSD/pkgsrc.git ; env PWD=${PWD}/pkgsrc git checkout pkgsrc-2017Q2
    - ls pkgsrc/bootstrap
    - pkgsrc/bootstrap/bootstrap --help
    - pkgsrc/bootstrap/bootstrap --prefix=${HOME}/pkg
    - PATH=${HOME}/pkg/sbin:${HOME}/pkg/bin:${PATH}
    - MANPATH=${HOME}/pkg/man:${MANPATH}
    - ls pkgsrc/*
    - ls ${HOME}/pkg

install:

before_script:

script:

after_success:
